<?php  exit();
/*
Page: /dedecms/
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'dsc  LIMIT 0,3' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (44) And  arc.arcrank > -1     ORDER BY arc.id dsc  LIMIT 0,3 </font>
Time2016-12-28 17:09:38
*/
?>
